name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install @capacitor/cli @capacitor/core
          npm install -g cordova

      - name: Sync Capacitor iOS
        run: npx cap sync ios

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS pods
        run: |
          cd ios
          pod install

      - name: Build IPA
        run: |
          cd ios/App
          xcodebuild -scheme App -workspace App.xcworkspace \
            -configuration Release \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            BUILD_DIR=build

      - name: Package IPA
        run: |
          cd ios/App/build/Release-iphoneos
          mkdir -p Payload
          cp -r App.app Payload/
          zip -r MyApp.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.ipa
          path: ios/App/build/Release-iphoneos/MyApp.ipa
